# =============================================================================
# Site Settings
# =============================================================================
title: "BeerBank3's DevNote"
description: "Python 개발자 beerbank3의 기술 블로그 & 학습 노트"
url: "https://beerbank3.github.io"
baseurl: ""

# =============================================================================
# Theme Settings
# =============================================================================
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# =============================================================================
# Search Settings
# =============================================================================
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# =============================================================================
# Navigation Settings
# =============================================================================
aux_links:
  "GitHub":
    - "https://github.com/beerbank3"

aux_links_new_tab: true
nav_sort: case_insensitive

# =============================================================================
# Footer Settings
# =============================================================================
footer_content: "Copyright &copy; 2025 beerbank3. Powered by Just the Docs."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# =============================================================================
# Collections Settings
# =============================================================================
collections:
  notes:
    permalink: "/notes/:name/"
    output: true
  snippets:
    permalink: "/snippets/:name/"
    output: true

# =============================================================================
# Default Front Matter
# =============================================================================
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
      nav_exclude: false
      
  - scope:
      path: "_notes"
      type: "notes"
    values:
      layout: "default"
      parent: "Notes"
      
  - scope:
      path: "_snippets"
      type: "snippets"
    values:
      layout: "default"
      parent: "Code Snippets"

# =============================================================================
# Plugins
# =============================================================================
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-include-cache

# =============================================================================
# Kramdown Settings
# =============================================================================
kramdown:
  syntax_highlighter_opts:
    default_lang: python
    block:
      line_numbers: true

# =============================================================================
# Build Settings
# =============================================================================
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Asia/Seoul

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

include:
  - _pages